// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	models "url_shortener/models"

	mock "github.com/stretchr/testify/mock"
)

// MockURLRepository is an autogenerated mock type for the URLRepository type
type MockURLRepository struct {
	mock.Mock
}

type MockURLRepository_Expecter struct {
	mock *mock.Mock
}

func (_m *MockURLRepository) EXPECT() *MockURLRepository_Expecter {
	return &MockURLRepository_Expecter{mock: &_m.Mock}
}

// Create provides a mock function with given fields: url
func (_m *MockURLRepository) Create(url *models.URL) error {
	ret := _m.Called(url)

	if len(ret) == 0 {
		panic("no return value specified for Create")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(*models.URL) error); ok {
		r0 = rf(url)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockURLRepository_Create_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Create'
type MockURLRepository_Create_Call struct {
	*mock.Call
}

// Create is a helper method to define mock.On call
//   - url *models.URL
func (_e *MockURLRepository_Expecter) Create(url interface{}) *MockURLRepository_Create_Call {
	return &MockURLRepository_Create_Call{Call: _e.mock.On("Create", url)}
}

func (_c *MockURLRepository_Create_Call) Run(run func(url *models.URL)) *MockURLRepository_Create_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(*models.URL))
	})
	return _c
}

func (_c *MockURLRepository_Create_Call) Return(_a0 error) *MockURLRepository_Create_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockURLRepository_Create_Call) RunAndReturn(run func(*models.URL) error) *MockURLRepository_Create_Call {
	_c.Call.Return(run)
	return _c
}

// FindByLongURL provides a mock function with given fields: longURL
func (_m *MockURLRepository) FindByLongURL(longURL string) (*models.URL, error) {
	ret := _m.Called(longURL)

	if len(ret) == 0 {
		panic("no return value specified for FindByLongURL")
	}

	var r0 *models.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.URL, error)); ok {
		return rf(longURL)
	}
	if rf, ok := ret.Get(0).(func(string) *models.URL); ok {
		r0 = rf(longURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(longURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLRepository_FindByLongURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByLongURL'
type MockURLRepository_FindByLongURL_Call struct {
	*mock.Call
}

// FindByLongURL is a helper method to define mock.On call
//   - longURL string
func (_e *MockURLRepository_Expecter) FindByLongURL(longURL interface{}) *MockURLRepository_FindByLongURL_Call {
	return &MockURLRepository_FindByLongURL_Call{Call: _e.mock.On("FindByLongURL", longURL)}
}

func (_c *MockURLRepository_FindByLongURL_Call) Run(run func(longURL string)) *MockURLRepository_FindByLongURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockURLRepository_FindByLongURL_Call) Return(_a0 *models.URL, _a1 error) *MockURLRepository_FindByLongURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLRepository_FindByLongURL_Call) RunAndReturn(run func(string) (*models.URL, error)) *MockURLRepository_FindByLongURL_Call {
	_c.Call.Return(run)
	return _c
}

// FindByShortURL provides a mock function with given fields: shortURL
func (_m *MockURLRepository) FindByShortURL(shortURL string) (*models.URL, error) {
	ret := _m.Called(shortURL)

	if len(ret) == 0 {
		panic("no return value specified for FindByShortURL")
	}

	var r0 *models.URL
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*models.URL, error)); ok {
		return rf(shortURL)
	}
	if rf, ok := ret.Get(0).(func(string) *models.URL); ok {
		r0 = rf(shortURL)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*models.URL)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(shortURL)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// MockURLRepository_FindByShortURL_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindByShortURL'
type MockURLRepository_FindByShortURL_Call struct {
	*mock.Call
}

// FindByShortURL is a helper method to define mock.On call
//   - shortURL string
func (_e *MockURLRepository_Expecter) FindByShortURL(shortURL interface{}) *MockURLRepository_FindByShortURL_Call {
	return &MockURLRepository_FindByShortURL_Call{Call: _e.mock.On("FindByShortURL", shortURL)}
}

func (_c *MockURLRepository_FindByShortURL_Call) Run(run func(shortURL string)) *MockURLRepository_FindByShortURL_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockURLRepository_FindByShortURL_Call) Return(_a0 *models.URL, _a1 error) *MockURLRepository_FindByShortURL_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *MockURLRepository_FindByShortURL_Call) RunAndReturn(run func(string) (*models.URL, error)) *MockURLRepository_FindByShortURL_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockURLRepository creates a new instance of MockURLRepository. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockURLRepository(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockURLRepository {
	mock := &MockURLRepository{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
